# Generated by Django 4.2.2 on 2023-08-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('Message', models.TextField(verbose_name='your user description')),
                ('Phone', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('Email', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('Subject', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='corep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('description', models.TextField(verbose_name='your user description')),
                ('fullname', models.CharField(help_text='max 20 character ', max_length=20, verbose_name='Your name(Author)')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/product', verbose_name='core img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='img/product', verbose_name='core img')),
                ('title2', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('title3', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('title4', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
            ],
            options={
                'verbose_name': 'corepost',
                'verbose_name_plural': 'All Movie Posts',
            },
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/product', verbose_name='core img')),
                ('title2', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('title3', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('title4', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
            ],
            options={
                'verbose_name': 'Featured',
                'verbose_name_plural': 'All Featured Posts',
            },
        ),
    ]
