# Generated by Django 4.2.2 on 2023-08-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(verbose_name='category name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(verbose_name='Manufacturer name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='shoppagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('is_new', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='new')),
                ('title', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your shop')),
                ('description', models.TextField(verbose_name='your user description')),
                ('is_adviced', models.BooleanField(default=True, verbose_name='do you like  this blog')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/product', verbose_name='blog img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='img/product', verbose_name='blog img')),
                ('the_price', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='mehsulun qiyməti')),
                ('sale', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='mehsulun endirimli qiyməti')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoping_categroy', to='product.category')),
                ('Manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoping_Manufacturer', to='product.manufacturer')),
            ],
            options={
                'verbose_name': 'şhopcard',
                'verbose_name_plural': 'All şhop Posts',
            },
        ),
    ]
