# Generated by Django 4.2.2 on 2023-08-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_color_shoppagemodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
