# Generated by Django 4.2.2 on 2023-08-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppagemodel',
            name='slug',
            field=models.CharField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
