# Generated by Django 4.2.2 on 2023-08-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_shoppagemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.CharField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
