# Generated by Django 4.2.2 on 2023-08-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_manufacturer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.CharField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
