# Generated by Django 4.2.2 on 2023-08-15 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your blog')),
                ('description', models.TextField(verbose_name='your user description')),
                ('is_adviced', models.BooleanField(default=True, verbose_name='do you like  this blog')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/product', verbose_name='blog img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='img/product', verbose_name='blog img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='img/product', verbose_name='blog img')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'All Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(verbose_name='category name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('commet', models.TextField(verbose_name='your user description')),
                ('Website', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('email', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_commet', to='blog.blogp')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'All Comment Posts',
            },
        ),
        migrations.AddField(
            model_name='blogp',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_category', to='blog.category'),
        ),
    ]
