# Generated by Django 4.2.2 on 2023-08-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(verbose_name='category name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogp',
            name='tags',
            field=models.ManyToManyField(to='blog.tags', verbose_name='Taglar:'),
        ),
    ]
