# Generated by Django 4.2.2 on 2023-08-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tags_blogp_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogp',
            name='title',
            field=models.CharField(help_text='max character limit 255', max_length=10000, verbose_name='Title of the your blog'),
        ),
    ]
