# Generated by Django 4.2.2 on 2023-08-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogp',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='your user description'),
        ),
        migrations.AlterField(
            model_name='blogp',
            name='tags',
            field=models.ManyToManyField(related_name='blog_tags', to='blog.tags', verbose_name='Taglar:'),
        ),
        migrations.AlterField(
            model_name='blogp',
            name='title',
            field=models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your blog'),
        ),
    ]
