# Generated by Django 4.2.2 on 2023-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='max 20 character ', max_length=20, verbose_name='Your name(Author)')),
                ('imdb', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='imdb reating')),
                ('is_adviced', models.BooleanField(default=True, verbose_name='do you like  this film')),
                ('genre', models.IntegerField(choices=[(0, 'Choose'), (1, 'Sci-fil'), (2, 'adventure'), (3, 'Dram')], default=0, verbose_name='Genre of you film')),
            ],
            options={
                'verbose_name': 'MoviePost',
                'verbose_name_plural': 'All Movie Posts',
            },
        ),
    ]
