# Generated by Django 4.2.2 on 2023-08-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moviep',
        ),
    ]
