# Generated by Django 4.2.2 on 2023-08-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_first_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email_Address',
        ),
    ]
