# Generated by Django 4.2.2 on 2023-08-28 12:09

from django.db import migrations
import user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_email_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.managers.CustomUserManager()),
            ],
        ),
    ]
