# Generated by Django 4.2.2 on 2023-08-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
