# Generated by Django 4.2.2 on 2023-09-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_moviep'),
        ('user', '0006_rename_last_name_user_last_name'),
    ]

    operations = [
    ]
